### ISSUE TITLE
[CrashLoopBackOff] Containers are repeatedly crashing after restarting

### ISSUE THREAD

**Issue by waitsj778** [GoogleCloudPlatform/solutions-speech-productionized-transcription#5]
### Issue Summary
Can't not deploy `Ingestor`, `Reviewer` by following [tutorial](https://cloud.google.com/architecture/architecture-for-production-ready-live-transcription-tutorial). When I deployed the microservices, Deployments `Ingestor`, `Reviewer` are repeatedly crashing after restarting with `CrashLoopBackOff`. After investigating container logs, I verified that the below error messages prevented the workloads from starting correctly:\
* Container log for ingestor [1] 
```
Traceback (most recent call last): File "/app/ingestor.py", line 23, in <module> from flask_socketio import SocketIO File "/usr/local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 24, in <module> from werkzeug.serving import run_with_reloader ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/usr/local/lib/python3.7/site-packages/werkzeug/serving.py)
```
* Container log for ingestor [2]
```
Traceback (most recent call last): File "/app/reviewer.py", line 21, in <module> from flask_socketio import SocketIO File "/usr/local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 24, in <module> from werkzeug.serving import run_with_reloader ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/usr/local/lib/python3.7/site-packages/werkzeug/serving.py)
```

It seems like the Python requirements are calling for flask-socketio==5.0.1, but that is outdated and tries to import the run_with_reloader incorrectly. The version should be updated to the latest version [5.1.1](https://pypi.org/project/Flask-SocketIO/#history).

### Repro
* Deployments `Ingestor`, `Reviewer` are repeatedly crashing after restarting with `CrashLoopBackOff`

![image](https://user-images.githubusercontent.com/30247846/161654042-76927b5d-ce40-4571-8ffc-033cf19de9b5.png)

* After updating flask-socketio version to the latest version 5.1.1
```
$ cd solutions-speech-productionized-transcription/
$ sed -i -e "s/5.0.1/5.1.1/g" ./ingest/requirements.txt ./reviewer/requirements.txt 
$ gcloud builds submit --config cloudbuild.yaml
$ kubectl delete -f k8s/ingestor.yaml,k8s/reviewer.yaml
$ kubectl apply -f k8s/ingestor.yaml,k8s/reviewer.yaml
```
![image](https://user-images.githubusercontent.com/30247846/161654847-1f774e6c-5652-4cae-afd5-7c8a683a67ce.png)

### Action Should Be Taken
Update `flask-socketio==5.0.1` to `flask-socketio==5.1.1` in both ingest/requirements.txt, reviewer/requirements.txt

**Comment by idofl** [comment]
Flask-SocketIO dependency had been updated. Issue fixed.

https://github.com/GoogleCloudPlatform/solutions-speech-productionized-transcription/commit/feea59d8979ef0817bed5d825edd0c0679cff0eb
